title: Hsien-Yeh Chen # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data analyst with 10-year experience in data collecting(census and sample), preparing, processing and sharing(visualizing). Proficient in SAS, Python, Tableau and SQL. Familiar with project management. 
  <br><br>
  <a href="https://www.linkedin.com/in/hsien-yeh-chen-6b652979/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
googleAnalytics: G-MKTLTP3WL2 # your Google Analytics tracking ID here
